name: generate animation

on:
  schedule:
    - cron: "0 */6 * * *"
    
  workflow_dispatch:

  push:
    branches: [ master ]

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
  build:
    runs-on: ubuntu-latest

    steps:
      - name: generate github-contribution-grid-snake.svg
        uses: avelycure/master
        with:
          github_user_name: avelycure
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v2.5.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
